const path = require('node:path')
const fs = require('node:fs')
const assert = require('node:assert/strict')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright')
async function main() {
  const output = path.resolve('output/playwright')
  fs.mkdirSync(output, { recursive: true })
  const { createServer } = await import('vite')
  const server = await createServer({ configFile: 'vite.renderer.config.ts', server: { host: '127.0.0.1', port: 5197, strictPort: true } })
  await server.listen()
  const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 800 } })
    const errors = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.addInitScript(() => {
      let vault = { version: 1, settings: { autoLockMinutes: 30, hidePasswordByDefault: true, clearClipboard: false }, websites: [{ id: 'site', name: 'ChatGPT 演示', url: 'https://example.com', category: '个人', tags: [], note: '', createdAt: '', updatedAt: '', accounts: [] }] }
      window.qa = { saves: 0, copied: '', opened: '' }
      window.desktopApi = {
        vault: {
          exists: async () => ({ success: true, data: true }),
          unlock: async () => ({ success: true, data: { data: vault, recoveredFromBackup: false } }),
          saveData: async (value) => { vault = JSON.parse(JSON.stringify(value)); window.qa.data = vault; window.qa.saves++; return { success: true } },
          lock: async () => ({ success: true })
        },
        app: { onAutoLock: () => {}, openExternal: async (url) => { window.qa.opened = url; return { success: true } } },
        clipboard: { copyText: async (value) => { window.qa.copied = value; return { success: true } }, clear: async () => {} }
      }
    })
    await page.goto('http://127.0.0.1:5197')
    await page.getByLabel('主密码', { exact: true }).fill('demo-only')
    await page.getByRole('button', { name: '立即解锁' }).click()
    await page.getByRole('button', { name: '新增账号', exact: true }).click()
    await page.getByLabel('用户名/邮箱', { exact: true }).fill('demo@example.com')
    await page.getByLabel('密码', { exact: true }).fill('website-demo')
    await page.getByLabel('验证邮箱（可选）').press('Enter')
    await page.getByRole('option', { name: '＋ 新增验证邮箱' }).click()
    await page.getByRole('option', { name: '＋ 新增验证邮箱' }).waitFor({ state: 'hidden' })
    assert.equal(await page.getByLabel('邮箱账号', { exact: true }).inputValue(), 'demo@example.com')
    await page.getByLabel('邮箱密码', { exact: true }).fill('mail-demo')
    await page.getByLabel('邮箱网页登录地址').fill('mail.example.com')
    await page.getByLabel('邮箱网页登录地址').press('Tab')
    await page.waitForFunction(() => document.getAnimations().every((animation) => animation.playState !== 'running'))
    await page.screenshot({ path: path.join(output, 'mailbox-form.png'), animations: 'disabled' })
    await page.getByRole('button', { name: '取消', exact: true }).click()
    assert.equal(await page.evaluate(() => window.qa.saves), 0)
    await page.getByRole('button', { name: '新增账号', exact: true }).click()
    assert.equal(await page.getByLabel('密码', { exact: true }).inputValue(), '')
    await page.getByLabel('用户名/邮箱', { exact: true }).fill('demo@example.com')
    await page.getByLabel('密码', { exact: true }).fill('website-demo')
    await page.getByLabel('验证邮箱（可选）').press('Enter')
    await page.getByRole('option', { name: '＋ 新增验证邮箱' }).click()
    await page.getByLabel('邮箱密码', { exact: true }).fill('mail-demo')
    await page.getByLabel('邮箱网页登录地址').fill('mail.example.com')
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await page.getByRole('button', { name: '复制邮箱密码', exact: true }).click()
    assert.equal(await page.evaluate(() => window.qa.copied), 'mail-demo')
    await page.getByRole('button', { name: '复制邮箱账号', exact: true }).click()
    assert.equal(await page.evaluate(() => window.qa.copied), 'demo@example.com')
    await page.getByRole('button', { name: '打开邮箱', exact: true }).click()
    assert.equal(await page.evaluate(() => window.qa.opened), 'https://mail.example.com/')
    await page.screenshot({ path: path.join(output, 'mailbox-detail.png') })
    await page.getByRole('button', { name: '邮箱管理', exact: true }).click()
    const dialog = page.getByRole('dialog')
    assert.equal(await dialog.getByRole('button', { name: '删除', exact: true }).isDisabled(), true)
    await dialog.getByRole('button', { name: '编辑', exact: true }).click()
    await page.getByLabel('邮箱密码', { exact: true }).fill('updated-demo')
    await page.getByRole('button', { name: '保存邮箱', exact: true }).click()
    await page.screenshot({ path: path.join(output, 'mailbox-manager.png') })
    await page.getByRole('button', { name: '关闭', exact: true }).click()
    await page.getByRole('button', { name: '复制邮箱密码', exact: true }).click()
    assert.equal(await page.evaluate(() => window.qa.copied), 'updated-demo')
    await page.getByRole('button', { name: '新增账号', exact: true }).click()
    await page.getByLabel('用户名/邮箱', { exact: true }).fill('second-account')
    await page.getByLabel('密码', { exact: true }).fill('second-demo')
    await page.getByLabel('验证邮箱（可选）').press('Enter')
    await page.getByRole('option', { name: 'demo@example.com', exact: true }).click()
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    assert.equal(await page.evaluate(() => window.qa.data.mailboxes.length), 1)
    assert.equal(await page.evaluate(() => window.qa.data.websites[0].accounts.length), 2)
    await page.getByLabel('搜索网站/账号', { exact: true }).fill('no-matching-site')
    await page.getByRole('button', { name: '邮箱管理', exact: true }).click()
    await page.getByRole('button', { name: /demo@example.com.*2 个关联账号/ }).click()
    const linkedAccount = page.getByRole('button', { name: '查看 ChatGPT 演示 的账号 second-account', exact: true })
    await linkedAccount.waitFor({ state: 'visible' })
    assert.equal(await page.getByRole('button', { name: /^查看 ChatGPT 演示 的账号/ }).count(), 2)
    await page.screenshot({ path: path.join(output, 'mailbox-links.png'), animations: 'disabled' })
    await linkedAccount.click()
    await page.getByRole('dialog').waitFor({ state: 'hidden' })
    assert.equal(await page.getByLabel('搜索网站/账号', { exact: true }).inputValue(), '')
    assert.ok((await page.locator('.linked-account-highlight').innerText()).includes('second-account'))
    await page.getByRole('button', { name: '锁定', exact: true }).click()
    await page.getByLabel('主密码', { exact: true }).fill('demo-only')
    await page.getByRole('button', { name: '立即解锁' }).click()
    await page.getByRole('button', { name: '复制邮箱密码', exact: true }).first().click()
    assert.equal(await page.evaluate(() => window.qa.copied), 'updated-demo')
    assert.deepEqual(errors, [])
    console.log('UI checks passed: inline creation, cancel/reset, shortcuts, shared edit, deletion guard, lock/unlock; no page errors.')
  } finally { await browser.close(); await server.close() }
}
main().catch((error) => { console.error(error); process.exitCode = 1 })
